server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/t_gorm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root

  jackson: #屏蔽null字段返回
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss #时间格式
    time-zone: GMT+8 #时区
